name: global-project

dependencies:
  - base
  - aeson
  - basement
  - cassava
  - Chart
  - Chart-diagrams
  - conduit
  - containers
  - diagrams
  - foundation
  - generics-eot
  - getopt-generics
  - graph-wrapper
  - http-client
  - interpolate
  - lens
  - optparse-applicative
  - pipes
  - rio
  - servant
  - servant-client
  - servant-server
  - shake
  - string-conversions
  - text
  - unordered-containers
  - vector
  - wai
  - warp
  - yaml
  - yesod

executables:
  dummy:
    main: dummy.hs
