name: my-xmonad

executables:
  xmonad-x86_64-linux:
    main: xmonad.hs
    source-dirs:
      - .
      - lib
    dependencies:
      - base
      - containers
      - directory
      - xmonad
      - xmonad-contrib
