add_newline = false
format = """
$shell\
$username\
$hostname\
$shlvl\
$kubernetes\
$directory\
$vcsh\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$docker_context\
$package\
$cmake\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$golang\
$helm\
$java\
$julia\
$kotlin\
$nim\
$nodejs\
$ocaml\
$perl\
$purescript\
$python\
$red\
$ruby\
$scala\
$swift\
$terraform\
$vlang\
$zig\
$nix_shell\
$conda\
$memory_usage\
$aws\
$gcloud\
$openstack\
$crystal\
$custom\
$cmd_duration\
$line_break\
$lua\
$jobs\
$battery\
$time\
$env_var\
$status\
$character"""

[git_commit]
only_detached = false
tag_disabled = false
commit_hash_length = 8

[character]
format = ' $symbol '
success_symbol = '[\$](bold green)'
error_symbol = '[\$](bold red)'
vicmd_symbol = '[:](bold green)'

[directory]
truncate_to_repo = false

[env_var.HOSTNAME]
format = "[HOSTNAME=$env_value](bold red)"

[status]
disabled = false
format = '[\($status\)](bold red)'

[shell]
disabled = false
format = '\($indicator\) '
