[general]
import = ["/home/shahn/.config/alacritty/colors.toml"]

[font]
size = 18.0

[font.bold]
family = "UbuntuMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "UbuntuMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "UbuntuMono Nerd Font"
style = "Italic"

[font.normal]
family = "UbuntuMono Nerd Font"
style = "Regular"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Control|Shift"

[mouse]
hide_when_typing = true

[scrolling]
history = 100000

[selection]
semantic_escape_chars = ",│`|\"' ()[]{}<>\t"

[terminal.shell]
program = "/usr/bin/zsh"

[window]
dynamic_padding = true
dynamic_title = true
title = "terminal"

[window.padding]
x = 5
y = 5

[hints]
alphabet = "enaritud"

[[hints.enabled]]
action = "Copy"
regex = '(https?://|mailto:)[a-zA-Z0-9.-]+(:\d+)?(/[a-zA-Z0-9._/%~#-]*)?'
binding.key = "U"
binding.mods = "Control"

[[hints.enabled]]
action = "Copy"
regex = "[a-z0-9/.][a-z0-9/._-]+"
binding.key = "F"
binding.mods = "Control"
