[[language]]
name = "nix"
auto-format = true
formatter = { command = "nixpkgs-fmt" }

# [[language]]
# name = "markdown"
# formatter = { command = 'prettier', args = ["--parser", "markdown"] }

[[language]]
name = "haskell"
auto-format = true
# formatter = { command = "zsh", args = ["-c", "fourmolu --stdin-input-file $(pwd)" ] }

[[language]]
name = "tsx"
auto-format = true
formatter = { command = 'prettier', args = ["--parser", "typescript"] }

[[language]]
name = "typescript"
auto-format = true
formatter = { command = 'prettier', args = ["--parser", "typescript"] }

[[language]]
name = "html"
formatter = { command = 'prettier', args = ["--parser", "html"] }

[[language]]
name = "css"
formatter = { command = 'prettier', args = ["--parser", "css"] }

[[language]]
name = "json"
formatter = { command = 'prettier', args = ["--parser", "json"] }

[[language]]
name = "yaml"
formatter = { command = 'prettier', args = ["--parser", "yaml"] }
auto-format = true

[[language]]
name = "jsonc"
formatter = { command = 'prettier', args = ["--parser", "jsonc"] }
